# Generated by Django 4.1 on 2024-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake',
            name='api_id',
            field=models.CharField(default=98765, max_length=11),
            preserve_default=False,
        ),
    ]
