# Generated by Django 5.1 on 2024-08-11 01:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthquakes', '0004_alter_earthquake_magnitude_userstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStatus',
            new_name='Status',
        ),
    ]
