# Generated by Django 5.1 on 2024-08-11 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthquakes', '0005_rename_userstatus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='earthquake_id',
            new_name='earthquake',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='person_id',
            new_name='user',
        ),
    ]
