# Generated by Django 5.1 on 2024-08-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquakes', '0006_rename_earthquake_id_status_earthquake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='earthquake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='earthquakes.earthquake'),
        ),
    ]
